name: C# (.Net) client CI
on:
  push:
    paths: clients/csharp/**
    branches: [ "master" ]
  pull_request:
    paths: clients/csharp/**
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd ${{ github.workspace }}/clients/csharp
        dotnet restore
    - name: Build
      run: |
        cd ${{ github.workspace }}/clients/csharp
        dotnet build --no-restore
    - name: Publish to nuget.org
      run: |
        cd ${{ github.workspace }}/clients/csharp
        dotnet nuget push ./src/SeleniumSessionClient/bin/Debug/**.nupkg --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
